# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20180826_1328'),
        ('addresses', '0003_auto_20180309_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
    ]
