# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_address_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
