# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20180826_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
    ]
