# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_picture/none/no_image_user.png', upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'User with this username already exists.'}, max_length=255, unique=True, validators=[users.validators.UsernameValidator()]),
        ),
    ]
