# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 06:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delivery_boy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_restaurant_user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
