# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_quantity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Recieved', 'Recieved'), ('Preparing', 'Preparing'), ('Cooked', 'Cooked')], default='New', max_length=32),
        ),
    ]
