# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20180605_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='status',
            field=models.CharField(default='New', max_length=32),
        ),
    ]
