# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20180623_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
