# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20180907_1109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quantity',
            table='quantities',
        ),
    ]
