# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_auto_20180309_0929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wishlist',
            table='wishlists',
        ),
    ]
