# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180605_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('Processing', 'Procecssing'), ('Shipped', 'Shipped'), ('Paid', 'Paid')], default='Recieved', max_length=120),
        ),
    ]
