# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-01 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180827_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('Processing', 'Processing'), ('Prepared', 'Prepared'), ('Shipped', 'Shipped'), ('Paid', 'Paid')], default='Recieved', max_length=120),
        ),
    ]
