# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_auto_20171202_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='dishes/'),
        ),
    ]
