# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-24 03:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180527_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
