# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-24 09:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=512, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
    ]
