# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-01 12:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180901_1158'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('other', django.db.models.manager.Manager()),
            ],
        ),
    ]
