# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-01 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180901_1214'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
